### ISSUE TITLE
RyanSB Lecture ideas

### ISSUE THREAD

**Issue by Nolski** [decause/hfoss#121]
- ofCourse overview
- Python beginner
- Python advanced
- fedora install-fest

**Comment by liam-middlebrook** [comment]
Tagging @ryansb

**Comment by ryansb** [comment]
- Putting the "sad" in "sysadmin": Why All Ops People are Alcoholics

**Comment by Nolski** [comment]
omg yes pls #shipit

**Comment by Nolski** [comment]
:sagittarius:
