### ISSUE TITLE
Week 17 on the syllabus has incorrect dates

### ISSUE THREAD

**Issue by Aalaizah** [decause/hfoss#133]
5/20 is the Wednesday of week 17. So Day 1 should be 5/18 and Day 2 should be 5/20.

**Comment by liam-middlebrook** [comment]
Do you mean week 12?

**Comment by ajman1101** [comment]
Is this using a Zero-based or normal (starting at 1) based weeks?

**Comment by Aalaizah** [comment]
Nope, the week of finals, it's labeled as 17 on the syllabus.

**Comment by Nolski** [comment]
I believe that 5/20 is the day of our final (which should be on a Wednesday and not follow our traditional schedule). @amm4108, you can check in SIS to confirm this. If that's the case, we can probably close this.

**Comment by Nolski** [comment]
So with further inquiry it looks like 5/20 is the day of our final which is why the schedule seems off. Unless anyone has any other comments, I'll be closing this.
