### ISSUE TITLE
Create advanced git lecture in syllabus

### ISSUE THREAD

**Issue by Nolski** [decause/hfoss#20]

**Comment by liam-middlebrook** [comment]
Maybe use this? http://rsb.io/talks/git/

Although I'm pretty sure it used to be in the content repo.

Or is that too beginner-level?

**Comment by sarahbethfederman** [comment]
@decause Git flow por favor!

**Comment by decause** [comment]
@sarahbethfederman hopefully we can get @ralphbean to stop by later on in the semester to drop a proper <code>git flow</code> guest lecture?
