### ISSUE TITLE
Add time for Dylan's security talk to schedule

### ISSUE THREAD

**Issue by dxa4481** [decause/hfoss#27]
I'd like to give a talk on basic web security if possible. @Nolski recommended I open an issue about it. I'm free either day.

**Comment by Nolski** [comment]
Good talk :+1:  Follow up and reopen on this issue if there is interest on running a guest lecture.

**Comment by dxa4481** [comment]
@Nolski There is a good chance of there being a guest lecture when @decause  is out of town. We talked a little about it today.

**Comment by Nolski** [comment]
@dxa4481 Cool. So for signing up for a guest lecture happens by submitting a pull request for syllabus.mak and filling in any spot that is marked TBA with your lecture [here](https://github.com/decause/hfoss/blob/master/templates/syllabus.mak#L94). Lemme know if you have any questions.
