### ISSUE TITLE
Typo on bugfix assignment

### ISSUE THREAD

**Issue by Nolski** [decause/hfoss#62]
It looks like the key for the bugfix assignment should be 

`bugfix1: <url>`
and not:
`bugfix: <url>`

but the [assignment page](https://github.com/decause/hfoss/blob/master/templates/hw/bugfix.mak#L119) says otherwise.

**Comment by liam-middlebrook** [comment]
It's also important to note that it should be within the `hw` dictionary in your YAML files, not just at the root level.

**Comment by IAmRasputin** [comment]
I was having some weird merge issues with my pull request for Quiz1, so that hasn't been merged yet, but I fixed that, and added [another commit or two](https://github.com/decause/hfoss/pull/50) fixing this.

**Comment by Nolski** [comment]
Awesome job @IAmRasputin. I'll close this.
