### ISSUE TITLE
mellolikejello's YAML is malformed

### ISSUE THREAD

**Issue by ryansb** [decause/hfoss#84]
See $subj @mellolikejello

**Comment by mellolikejello** [comment]
all students missing `name` field

**Comment by ryansb** [comment]
...why doesn't anyone have a name field?

**Comment by Nolski** [comment]
I would guess it's because the example yaml doesn't have a name field.

https://github.com/decause/hfoss/blob/master/people/2015/spring/fake_student.yaml

**Comment by ryansb** [comment]
:( Well that'll do it. 

@decause can you please have the class fill in their names if they want profiles to work?

**Comment by mellolikejello** [comment]
Fixed in #85
